# Relevant files

INITIAL_CONDITION_DIRECTORY = "our_solar_system"
OUTPUT_DIRECTORY = "inclination_test"
OUTPUT_FILE_BASE = "snapshot"


# Run Characteristics

BEGIN_TIME = 0.0

MAX_TIME = (5.2004186 * 10**9)
MAX_TIME_STEP = 86400.0
OUTPUT_TIME_STEP = 144456

TIME_OF_FIRST_OUTPUT = 0.0


# Units

GRAVITATIONAL_CONSTANT = 6.67384 * (10 ** (-11))

# Options
INTEGRATOR = 'verlet'

# Pack everything
params = {'INITIAL_CONDITION_DIRECTORY': INITIAL_CONDITION_DIRECTORY,
          'OUTPUT_DIRECTORY': OUTPUT_DIRECTORY,
          'OUTPUT_FILE_BASE': OUTPUT_FILE_BASE,
          'BEGIN_TIME': BEGIN_TIME,
          'MAX_TIME': MAX_TIME,
          'MAX_TIME_STEP': MAX_TIME_STEP,
          'OUTPUT_TIME_STEP': OUTPUT_TIME_STEP,
          'TIME_OF_FIRST_OUTPUT': TIME_OF_FIRST_OUTPUT,
          'GRAVITATIONAL_CONSTANT': GRAVITATIONAL_CONSTANT,
          'INTEGRATOR': INTEGRATOR}
