SIM_NAME = "all_planet_plane_test"
VID_NAME = "first_full_test"
SNAPSHOT_START = 0
SNAPSHOT_END = 15036
RESOLUTION = (1920, 1080)

params = {"SIM_NAME": SIM_NAME,
          "VID_NAME": VID_NAME,
          "SNAPSHOT_START": SNAPSHOT_START,
          "SNAPSHOT_END": SNAPSHOT_END,
          "RESOLUTION": RESOLUTION}